TERMINOLOGY = { 
"Algorithm": "A step-by-step procedure for solving a problem or performing a task",
               "Array": "A collection of items stored at contiguous memory locations",
               "Boolean": "A data type that can hold true or false values",
               "Class": "A blueprint for creating objects in object-oriented programming",
               "Compiler": "A program that translates source code into machine code",
               "Debugging": "The process of identifying and removing errors from code",
              "Encapsulation": "Bundling data and methods that operate on the data within one unit",
              "Function": "A block of code designed to perform a specific task",
              "Inheritance": "A mechanism where a new class derives properties from an existing class",
              "Interface": "A shared boundary across which two or more separate components exchange information",
               "Library": "A collection of precompiled routines that a program can use",
               "Loop": "A sequence of instructions that repeats until a certain condition is met",
               "Method": "A function associated with an object in object-oriented programming",
               "Object": "An instance of a class containing data and methods",
               "Parameter": "A variable used to pass information into a function",
               "Recursion": "A method where the solution to a problem depends on solutions to smaller instances of the same problem",
               "Syntax": "The set of rules that defines the combinations of symbols in a programming language",
               "Variable": "A storage location identified by a name that can hold data",
               "Framework": "A platform for developing software applications with predefined structures",
               "Source Code": "The human-readable instructions written in a programming language",
              "Thread": "A sequence of programmed instructions that can be managed independently by a scheduler",
              "API (Application Programming Interface)": "A set of rules that allows different software",
              "Reinforced Concrete": "A composite material that combines the compressive strength of concrete with the tensile strength of steel reinforcement (rebars), widely used in structures such as buildings, bridges, and highways.", 
             "Foundation": "The lowest load-bearing part of a structure that transmits and distributes the building loads to the underlying soil or rock, ensuring stability and preventing settlement.", 
             "Load-Bearing Wall": "A wall that supports not only its own weight but also additional loads from the roof, floors, and other structural elements, contributing to the overall stability of a building.", 
             "Structural Analysis": "The process of determining the effects of loads and forces on a structure’s components to ensure that it can safely withstand the applied loads without failure.", 
             "Shear Force": "An internal force within a structural element that causes adjacent sections to slide past one another, critical in assessing a structure's ability to resist deformation.", 
             "Bending Moment": "A measure of the bending effect produced by forces acting on a structural element, typically calculated as the product of force and the perpendicular distance from a specified point, essential for designing beams and columns.", 
             "Geotechnical Engineering": "A branch of civil engineering that focuses on the behavior of earth materials (soil and rock) and their interaction with man-made structures, including site investigations and foundation design.", 
             "Drainage System": "An infrastructure system designed to remove excess water from areas such as roads, construction sites, and urban landscapes, thereby preventing flooding and maintaining the integrity of the structures",}
               
x = input( "HI, IM THE ENGINEERING DICTORY! WHAT WORD DO YOU WANT TO KNOW ABOUT ENGINEERING?")

print(TERMINOLOGY[x])
